# Header
nav:
  Posts: /archives
  Categories: /categories
  Tags: /tags

# favicon
favicon: /images/logo.svg

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/bitsealog/

# analytics
google_analytics:

# maple
maple:
  enable: false
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5
