# Header
nav:
  Posts: /archives
  Categories: /categories
  Tags: /tags

# favicon
favicon: /images/logo.svg

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/eltonyuen/

# analytics
google_analytics:

# false
fancybox: false
